#!/bin/sh

# Copyright (C) 2010 - astera <astera@siliconninjas.net>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation version 3 of the License
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

if [ -e /etc/init.d/tomcat5 ]; then
  my_tomcat='tomcat5'
else
  my_tomcat='tomcat5.5'
fi
    
echo -n "Restarting Tomcat, plz hold..."
sudo /etc/init.d/$my_tomcat restart

exit 0

